spring:
  datasource:
    hikari:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: dbc:oracle:thin:@localhost:1521:xe
      username: simple
      password: 1234
      maximum-pool-size: 10
      connection-timeout: 10000
      connection-test-query: SELECT 1 FROM DUAL
      auto-commit: false
      max-lifetime: 30000


  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        xlxs: application/vnd.ms-excel
    view:
      prefix: /WEB-INF/views
      suffix: .jsp


  devtools:
    livereload:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/**.xml

server:
  port: 8443
  servlet:
    context-path: /
