spring:
  datasource:
    hikari:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:xe
      username: simple
      password: simple
      maximum-pool-size: 10
      connection-timeout: 10000
      connection-test-query: SELECT 1 FROM DUAL
      auto-commit: false
      max-lifetime: 30000

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        xlxs: application/vnd.ms-excel
    view:
      prefix: /WEB-INF/views
      suffix: .jsp

  devtools:
    livereload:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/**.xml

server:
  port: 8443
  servlet:
    context-path: /
  ssl:
    enabled: true
    key-store: .keystore
    key-store-password: cucon#321

  error:
    include-exception: false
    include-stacktrace: never
    path: /error
    whitelabel:
      enabled: true
